// theo token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg4ZDEzODEyYzdhYmE2NTdjZDk1Y2EiLCJmdWxsbmFtZSI6IlRoZW8gU2FhZCIsImVtYWlsIjoidGhlb0BtaXUuZWR1IiwiaWF0IjoxNjg2Njg4MDY1fQ.otVQ9IbyEcizGq3aecJfgfwJKr5bWIVClxSDPcc_Bdw
// asaad token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg4Y2E5MzIwOGQxNjgyMDVlZTVjODQiLCJmdWxsbmFtZSI6IkFzYWFkIFNhYWQiLCJlbWFpbCI6ImFzYWFkQG1pdS5lZHUiLCJpYXQiOjE2ODY2ODc4OTR9.mDqiMQqlPKyHrzjPrCCeDB6GAyK0EfY7rM1ewImgiNk

POST http://localhost:3000/groups
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg4Y2E5MzIwOGQxNjgyMDVlZTVjODQiLCJmdWxsbmFtZSI6IkFzYWFkIFNhYWQiLCJlbWFpbCI6ImFzYWFkQG1pdS5lZHUiLCJpYXQiOjE2ODY2ODc4OTR9.mDqiMQqlPKyHrzjPrCCeDB6GAyK0EfY7rM1ewImgiNk

{
    "title": "Florida Trip"
}
###

GET http://localhost:3000/groups
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg4Y2E5MzIwOGQxNjgyMDVlZTVjODQiLCJmdWxsbmFtZSI6IkFzYWFkIFNhYWQiLCJlbWFpbCI6ImFzYWFkQG1pdS5lZHUiLCJpYXQiOjE2ODY2ODc4OTR9.mDqiMQqlPKyHrzjPrCCeDB6GAyK0EfY7rM1ewImgiNk

###

POST http://localhost:3000/groups/6488d0f512c7aba657cd95c7/members
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg4Y2E5MzIwOGQxNjgyMDVlZTVjODQiLCJmdWxsbmFtZSI6IkFzYWFkIFNhYWQiLCJlbWFpbCI6ImFzYWFkQG1pdS5lZHUiLCJpYXQiOjE2ODY2ODc4OTR9.mDqiMQqlPKyHrzjPrCCeDB6GAyK0EfY7rM1ewImgiNk

{
    "email": "theo@miu.edu"
}

###
GET http://localhost:3000/groups?pending=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg4ZDEzODEyYzdhYmE2NTdjZDk1Y2EiLCJmdWxsbmFtZSI6IlRoZW8gU2FhZCIsImVtYWlsIjoidGhlb0BtaXUuZWR1IiwiaWF0IjoxNjg2Njg4MDY1fQ.otVQ9IbyEcizGq3aecJfgfwJKr5bWIVClxSDPcc_Bdw


###
GET http://localhost:3000/groups/6488d0f512c7aba657cd95c7/members/6488d13812c7aba657cd95ca
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2NDg4ZDEzODEyYzdhYmE2NTdjZDk1Y2EiLCJmdWxsbmFtZSI6IlRoZW8gU2FhZCIsImVtYWlsIjoidGhlb0BtaXUuZWR1IiwiaWF0IjoxNjg2Njg4MDY1fQ.otVQ9IbyEcizGq3aecJfgfwJKr5bWIVClxSDPcc_Bdw